/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as SignupIndexImport } from './routes/signup/index'
import { Route as SigninIndexImport } from './routes/signin/index'
import { Route as NewIndexImport } from './routes/new/index'
import { Route as GettingStartedIndexImport } from './routes/getting-started/index'
import { Route as EditorIndexImport } from './routes/editor/index'
import { Route as AuthenticatedCreateIndexImport } from './routes/_authenticated/create/index'
import { Route as EditorSplatResumeIdImport } from './routes/editor/$.resumeId'
import { Route as AuthenticatedDashboardv2LayoutImport } from './routes/_authenticated/dashboard_v2/_layout'
import { Route as AuthenticatedDashboardLayoutImport } from './routes/_authenticated/dashboard/_layout'
import { Route as AuthenticatedDashboardv2LayoutIndexImport } from './routes/_authenticated/dashboard_v2/_layout/index'
import { Route as AuthenticatedDashboardLayoutIndexImport } from './routes/_authenticated/dashboard/_layout/index'
import { Route as AuthenticatedDashboardLayoutResumesRouteImport } from './routes/_authenticated/dashboard/_layout/resumes/route'
import { Route as AuthenticatedDashboardLayoutEditorRouteImport } from './routes/_authenticated/dashboard/_layout/editor/route'

// Create Virtual Routes

const AuthenticatedDashboardv2Import = createFileRoute(
  '/_authenticated/dashboard_v2',
)()
const AuthenticatedDashboardImport = createFileRoute(
  '/_authenticated/dashboard',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardv2Route = AuthenticatedDashboardv2Import.update({
  id: '/dashboard_v2',
  path: '/dashboard_v2',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const NewIndexRoute = NewIndexImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRoute,
} as any)

const GettingStartedIndexRoute = GettingStartedIndexImport.update({
  id: '/getting-started/',
  path: '/getting-started/',
  getParentRoute: () => rootRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedCreateIndexRoute = AuthenticatedCreateIndexImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const EditorSplatResumeIdRoute = EditorSplatResumeIdImport.update({
  id: '/editor/$/resumeId',
  path: '/editor/$/resumeId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardv2LayoutRoute =
  AuthenticatedDashboardv2LayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedDashboardv2Route,
  } as any)

const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const AuthenticatedDashboardv2LayoutIndexRoute =
  AuthenticatedDashboardv2LayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardv2LayoutRoute,
  } as any)

const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

const AuthenticatedDashboardLayoutResumesRouteRoute =
  AuthenticatedDashboardLayoutResumesRouteImport.update({
    id: '/resumes',
    path: '/resumes',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

const AuthenticatedDashboardLayoutEditorRouteRoute =
  AuthenticatedDashboardLayoutEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
    '/getting-started/': {
      id: '/getting-started/'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedIndexImport
      parentRoute: typeof rootRoute
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewIndexImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/_layout': {
      id: '/_authenticated/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard_v2': {
      id: '/_authenticated/dashboard_v2'
      path: '/dashboard_v2'
      fullPath: '/dashboard_v2'
      preLoaderRoute: typeof AuthenticatedDashboardv2Import
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard_v2/_layout': {
      id: '/_authenticated/dashboard_v2/_layout'
      path: '/dashboard_v2'
      fullPath: '/dashboard_v2'
      preLoaderRoute: typeof AuthenticatedDashboardv2LayoutImport
      parentRoute: typeof AuthenticatedDashboardv2Route
    }
    '/editor/$/resumeId': {
      id: '/editor/$/resumeId'
      path: '/editor/$/resumeId'
      fullPath: '/editor/$/resumeId'
      preLoaderRoute: typeof EditorSplatResumeIdImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create/': {
      id: '/_authenticated/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/_layout/editor': {
      id: '/_authenticated/dashboard/_layout/editor'
      path: '/editor'
      fullPath: '/dashboard/editor'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutEditorRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
    '/_authenticated/dashboard/_layout/resumes': {
      id: '/_authenticated/dashboard/_layout/resumes'
      path: '/resumes'
      fullPath: '/dashboard/resumes'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutResumesRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
    '/_authenticated/dashboard/_layout/': {
      id: '/_authenticated/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
    '/_authenticated/dashboard_v2/_layout/': {
      id: '/_authenticated/dashboard_v2/_layout/'
      path: '/'
      fullPath: '/dashboard_v2/'
      preLoaderRoute: typeof AuthenticatedDashboardv2LayoutIndexImport
      parentRoute: typeof AuthenticatedDashboardv2LayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutEditorRouteRoute: typeof AuthenticatedDashboardLayoutEditorRouteRoute
  AuthenticatedDashboardLayoutResumesRouteRoute: typeof AuthenticatedDashboardLayoutResumesRouteRoute
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutEditorRouteRoute:
      AuthenticatedDashboardLayoutEditorRouteRoute,
    AuthenticatedDashboardLayoutResumesRouteRoute:
      AuthenticatedDashboardLayoutResumesRouteRoute,
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLayoutRoute:
      AuthenticatedDashboardLayoutRouteWithChildren,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedDashboardv2LayoutRouteChildren {
  AuthenticatedDashboardv2LayoutIndexRoute: typeof AuthenticatedDashboardv2LayoutIndexRoute
}

const AuthenticatedDashboardv2LayoutRouteChildren: AuthenticatedDashboardv2LayoutRouteChildren =
  {
    AuthenticatedDashboardv2LayoutIndexRoute:
      AuthenticatedDashboardv2LayoutIndexRoute,
  }

const AuthenticatedDashboardv2LayoutRouteWithChildren =
  AuthenticatedDashboardv2LayoutRoute._addFileChildren(
    AuthenticatedDashboardv2LayoutRouteChildren,
  )

interface AuthenticatedDashboardv2RouteChildren {
  AuthenticatedDashboardv2LayoutRoute: typeof AuthenticatedDashboardv2LayoutRouteWithChildren
}

const AuthenticatedDashboardv2RouteChildren: AuthenticatedDashboardv2RouteChildren =
  {
    AuthenticatedDashboardv2LayoutRoute:
      AuthenticatedDashboardv2LayoutRouteWithChildren,
  }

const AuthenticatedDashboardv2RouteWithChildren =
  AuthenticatedDashboardv2Route._addFileChildren(
    AuthenticatedDashboardv2RouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDashboardv2Route: typeof AuthenticatedDashboardv2RouteWithChildren
  AuthenticatedCreateIndexRoute: typeof AuthenticatedCreateIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDashboardv2Route: AuthenticatedDashboardv2RouteWithChildren,
  AuthenticatedCreateIndexRoute: AuthenticatedCreateIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/editor': typeof EditorIndexRoute
  '/getting-started': typeof GettingStartedIndexRoute
  '/new': typeof NewIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/dashboard_v2': typeof AuthenticatedDashboardv2LayoutRouteWithChildren
  '/editor/$/resumeId': typeof EditorSplatResumeIdRoute
  '/create': typeof AuthenticatedCreateIndexRoute
  '/dashboard/editor': typeof AuthenticatedDashboardLayoutEditorRouteRoute
  '/dashboard/resumes': typeof AuthenticatedDashboardLayoutResumesRouteRoute
  '/dashboard/': typeof AuthenticatedDashboardLayoutIndexRoute
  '/dashboard_v2/': typeof AuthenticatedDashboardv2LayoutIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/editor': typeof EditorIndexRoute
  '/getting-started': typeof GettingStartedIndexRoute
  '/new': typeof NewIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutIndexRoute
  '/dashboard_v2': typeof AuthenticatedDashboardv2LayoutIndexRoute
  '/editor/$/resumeId': typeof EditorSplatResumeIdRoute
  '/create': typeof AuthenticatedCreateIndexRoute
  '/dashboard/editor': typeof AuthenticatedDashboardLayoutEditorRouteRoute
  '/dashboard/resumes': typeof AuthenticatedDashboardLayoutResumesRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/editor/': typeof EditorIndexRoute
  '/getting-started/': typeof GettingStartedIndexRoute
  '/new/': typeof NewIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/_layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/dashboard_v2': typeof AuthenticatedDashboardv2RouteWithChildren
  '/_authenticated/dashboard_v2/_layout': typeof AuthenticatedDashboardv2LayoutRouteWithChildren
  '/editor/$/resumeId': typeof EditorSplatResumeIdRoute
  '/_authenticated/create/': typeof AuthenticatedCreateIndexRoute
  '/_authenticated/dashboard/_layout/editor': typeof AuthenticatedDashboardLayoutEditorRouteRoute
  '/_authenticated/dashboard/_layout/resumes': typeof AuthenticatedDashboardLayoutResumesRouteRoute
  '/_authenticated/dashboard/_layout/': typeof AuthenticatedDashboardLayoutIndexRoute
  '/_authenticated/dashboard_v2/_layout/': typeof AuthenticatedDashboardv2LayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/editor'
    | '/getting-started'
    | '/new'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/dashboard_v2'
    | '/editor/$/resumeId'
    | '/create'
    | '/dashboard/editor'
    | '/dashboard/resumes'
    | '/dashboard/'
    | '/dashboard_v2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/editor'
    | '/getting-started'
    | '/new'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/dashboard_v2'
    | '/editor/$/resumeId'
    | '/create'
    | '/dashboard/editor'
    | '/dashboard/resumes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/editor/'
    | '/getting-started/'
    | '/new/'
    | '/signin/'
    | '/signup/'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/_layout'
    | '/_authenticated/dashboard_v2'
    | '/_authenticated/dashboard_v2/_layout'
    | '/editor/$/resumeId'
    | '/_authenticated/create/'
    | '/_authenticated/dashboard/_layout/editor'
    | '/_authenticated/dashboard/_layout/resumes'
    | '/_authenticated/dashboard/_layout/'
    | '/_authenticated/dashboard_v2/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EditorIndexRoute: typeof EditorIndexRoute
  GettingStartedIndexRoute: typeof GettingStartedIndexRoute
  NewIndexRoute: typeof NewIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  EditorSplatResumeIdRoute: typeof EditorSplatResumeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EditorIndexRoute: EditorIndexRoute,
  GettingStartedIndexRoute: GettingStartedIndexRoute,
  NewIndexRoute: NewIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  EditorSplatResumeIdRoute: EditorSplatResumeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/editor/",
        "/getting-started/",
        "/new/",
        "/signin/",
        "/signup/",
        "/editor/$/resumeId"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/dashboard_v2",
        "/_authenticated/create/"
      ]
    },
    "/editor/": {
      "filePath": "editor/index.tsx"
    },
    "/getting-started/": {
      "filePath": "getting-started/index.tsx"
    },
    "/new/": {
      "filePath": "new/index.tsx"
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/signup/": {
      "filePath": "signup/index.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/dashboard/_layout"
      ]
    },
    "/_authenticated/dashboard/_layout": {
      "filePath": "_authenticated/dashboard/_layout.tsx",
      "parent": "/_authenticated/dashboard",
      "children": [
        "/_authenticated/dashboard/_layout/editor",
        "/_authenticated/dashboard/_layout/resumes",
        "/_authenticated/dashboard/_layout/"
      ]
    },
    "/_authenticated/dashboard_v2": {
      "filePath": "_authenticated/dashboard_v2",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/dashboard_v2/_layout"
      ]
    },
    "/_authenticated/dashboard_v2/_layout": {
      "filePath": "_authenticated/dashboard_v2/_layout.tsx",
      "parent": "/_authenticated/dashboard_v2",
      "children": [
        "/_authenticated/dashboard_v2/_layout/"
      ]
    },
    "/editor/$/resumeId": {
      "filePath": "editor/$.resumeId.tsx"
    },
    "/_authenticated/create/": {
      "filePath": "_authenticated/create/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/_layout/editor": {
      "filePath": "_authenticated/dashboard/_layout/editor/route.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard/_layout/resumes": {
      "filePath": "_authenticated/dashboard/_layout/resumes/route.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard/_layout/": {
      "filePath": "_authenticated/dashboard/_layout/index.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard_v2/_layout/": {
      "filePath": "_authenticated/dashboard_v2/_layout/index.tsx",
      "parent": "/_authenticated/dashboard_v2/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
